### ISSUE TITLE
Mod crashes when left-clicking probably all kinds of Tile Entities

### ISSUE THREAD

**Issue by ChromaPIE** [pokmon987/HammerAndVil#8]
Tested by left clicking the ducts from Thermal Dynamics and generators from Simple Generators (In fact I was trying to break them).

Here is the crash report generated after the first crash which immediately happened when trying to break a Thermal Dynamics duct:
https://paste.ubuntu.com/p/NpGWNbbTgn/

The issue is obviously fatal. Begging for a fix as I really love its design and already made scripts based on it.

**Comment by pokmon987** [comment]
I've fixed it, but I'm also trying to finish some other pieces of code that I've changed, I'll try to get it pushed as soon as I can.

**Comment by ChromaPIE** [comment]
Appreciate that.
